name: PythonCi

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.23
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.23
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install nose
        pip install coverage
    - name: Running nosetests
      run: |
        nosetests --with-coverage --cover-erase --cover-min-percentage=70
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=.pylintrc cmake_project_creator

